### ISSUE TITLE
[ Feature Request] Version info when choosing version

### ISSUE THREAD

**Issue by light24bulbs** [usbkey9/uktools#11]
Hey, this is a great tool!

  It could be awesome if when giving you the choice of kernel version, it told you what the version numbers were for each choice( stable, RC, and testing).  I realize this is probably another network call and more work to write, but if you have contributors or something it could be a cool additional feature.

**Comment by usbkey9** [comment]
Hi @light24bulbs,

Too many works for the benefits, sorry
