### ISSUE TITLE
Change of ubuntu kernel archive structure (from v5.7.2 onward)

### ISSUE THREAD

**Issue by tomdierkes** [usbkey9/uktools#14]
Seems that Ubuntu has changed their kernel archive structure (again?):
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7.2 has now additional subdirs (amd64/, arm64/, armhf/, ...).
As a result, the checksum mechanism is not working anymore in the upgrade script since the checksums are placed into these new  subdirs respectively and hence, no upgrade to any new kernels are done.
These tools have been working like a charm; it would be a great pity leaving them broken as they are ...

**Comment by ildella** [comment]
@usbkey9 how can I contribute a patch?

**Comment by ildella** [comment]
Right, I made the PR https://github.com/usbkey9/uktools/pull/15 :) 

There's still the extra-"echo", that worked for me on Ubuntu 20.04 to upgrade to latest 5.7.6 which I am running now. 
BTW I have very little knowledge of the extent of this tool so that most likely breaks other distro...

**Comment by usbkey9** [comment]
Hi Ildella,

Your contribution is welcome but you have to add a condition that adapt the behavior since v5.7.2
Once done, I will be happy to accept your MR

Best

**Comment by ildella** [comment]
I made the change, would that be ok?

**Comment by usbkey9** [comment]
Fixed it https://github.com/usbkey9/uktools/commit/bb8fb2b32860bd615f47549e9a8b2c90a3a851be
