### ISSUE TITLE
Kernel upgrade don't work - Ubuntu 16.04

### ISSUE THREAD

**Issue by nmarjanovic** [usbkey9/uktools#6]
Hi,

This is output:

Setting up linux-headers-4.16.8-041608 (4.16.8-041608.201805090431) ...
id: extra operand ‘username’
Try 'id --help' for more information.

Thanks

**Comment by usbkey9** [comment]
Hi,

What's your username pls ?

**Comment by nmarjanovic** [comment]
User name is my Linux system user, not root of course. Even if you run do-kernel-upgrade command with sudo, you will get same output.

**Comment by usbkey9** [comment]
First, don't worry, this error occur when script have to notify you that kernel was upgrade. So everything is fine, except notification.
Second, how did you do to set a username with space ?? (I understood that "user name" is your account name, right ?)

**Comment by usbkey9** [comment]
Can you attach `id -run` result please because it's not possible to set a username with space

**Comment by nmarjanovic** [comment]
Look, not sure  what issue is, but you said that even with  this "error" kernel will be upgraded, but that is not true, uname -a give me output "Linux BRE-PORT03 4.13.0-41-generic", and yes laptop was rebooted, do-kernel-upgrade try to install 4.16, but stop with error provided before.

id -run = username
w -h | awk '{print $1}' = will print few times same username

**Comment by usbkey9** [comment]
Btw, I fixed notification bug
